@echo off
echo Starting TutorAgent Dashboard...
echo ensuring dependencies...
python -m pip install streamlit pandas requests > nul 2>&1
echo Launching Streamlit...
python -m streamlit run dashboard.py
pause
